Aplikasi/CRUD/App/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^Sesi/$',views.list,name='list'),
    url(r'^Sesi/create/$',views.create,name='create'),
    url(r'^Sesi/delete/(?P<delete_id>[0-9])$',views.delete,name='delete'),
    url(r'^Sesi/update/(?P<update_id>[0-9])$',views.update,name='update'),


    url(r'^Pengajar/$',views.listpengajar,name='listpengajar'),
    url(r'^Pengajar/create/$',views.createpengajar,name='createpengajar'),
    url(r'^Pengajar/delete/(?P<delete_id>[0-9])$',views.deletepengajar,name='deletepengajar'),
    url(r'^Pengajar/update/(?P<update_id>[0-9])$',views.updatepengajar,name='updatepengajar'),


    url(r'^Kelas/$',views.listkelas,name='listkelas'),
    url(r'^Kelas/create/$',views.createkelas,name='createkelas'),
    url(r'^Kelas/delete/(?P<delete_id>[0-9])$',views.deletekelas,name='deletekelas'),
    url(r'^Kelas/update/(?P<update_id>[0-9])$',views.updatekelas,name='updatekelas'),


    url(r'^Matkul/$',views.listmatakuliah,name='listmatakuliah'),
    url(r'^Matkul/create/$',views.creatematakuliah,name='creatematakuliah'),
    url(r'^Matkul/delete/(?P<delete_id>[0-9])$',views.deletematakuliah,name="deletematakuliah"),
    url(r'^Matkul/update/(?P<update_id>[0-9])$',views.updatematakuliah,name='updatematakuliah'),


    url(r'^Akun/$',views.listakun,name='listakun'),
    url(r'^Akun/create/$',views.createakun,name='createakun'),
    url(r'^Akun/delete/(?P<delete_id>[0-9])$',views.deleteakun,name='deleteakun'),
    url(r'^Akun/update/(?P<update_id>[0-9])$',views.updateakun,name='updateakun'),

]

Aplikasi/CRUD/CRUD/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^App/', include(('App.urls', 'App'), namespace='App')),
]

Aplikasi/CRUD/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title %}
          
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Penjadwalan</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App:listmatakuliah' %}">Matakuliah</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App:listkelas' %}">Kelas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App:listpengajar' %}">Pengajar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App:list' %}">Sesi</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App:listakun' %}">Akun</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block contents %}
      
    {% endblock contents %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

Aplikasi/CRUD/templates/index.html
{% extends "base.html" %}

{% block title %}
  {{page_title}}
{% endblock title %}

{% block contents %}
    <h1>{{page_title}}</h1>
{% endblock contents %}