Aplikasi/CRUD/App/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^Sesi/$',views.list,name='list'),
    url(r'^Sesi/create/$',views.create,name='create'),
    url(r'^Sesi/delete/(?P<delete_id>[0-9])$',views.delete,name='delete'),
    url(r'^Sesi/update/(?P<update_id>[0-9])$',views.update,name='update'),


    url(r'^Pengajar/$',views.listpengajar,name='listpengajar'),
    url(r'^Pengajar/create/$',views.createpengajar,name='createpengajar'),
    url(r'^Pengajar/delete/(?P<delete_id>[0-9])$',views.deletepengajar,name='deletepengajar'),
    url(r'^Pengajar/update/(?P<update_id>[0-9])$',views.updatepengajar,name='updatepengajar'),


    url(r'^Kelas/$',views.listkelas,name='listkelas'),
    url(r'^Kelas/create/$',views.createkelas,name='createkelas'),
    url(r'^Kelas/delete/(?P<delete_id>[0-9])$',views.deletekelas,name='deletekelas'),
    url(r'^Kelas/update/(?P<update_id>[0-9])$',views.updatekelas,name='updatekelas'),


    url(r'^Matkul/$',views.listmatakuliah,name='listmatakuliah'),
    url(r'^Matkul/create/$',views.creatematakuliah,name='creatematakuliah'),
    url(r'^Matkul/delete/(?P<delete_id>[0-9])$',views.deletematakuliah,name="deletematakuliah"),
    url(r'^Matkul/update/(?P<update_id>[0-9])$',views.updatematakuliah,name='updatematakuliah'),


    url(r'^Akun/$',views.listakun,name='listakun'),
    url(r'^Akun/create/$',views.createakun,name='createakun'),
    url(r'^Akun/delete/(?P<delete_id>[0-9])$',views.deleteakun,name='deleteakun'),
    url(r'^Akun/update/(?P<update_id>[0-9])$',views.updateakun,name='updateakun'),

]

Aplikasi/CRUD/CRUD/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^App/', include(('App.urls', 'App'), namespace='App')),
]

Aplikasi/CRUD/App/templates/kelas/create.html
{% extends "base.html" %}

{% block title %}
    {{page_title}}
{% endblock title %}


{% block contents %}
    <div class="container shadow-lg p-3 mb-5 bg-white rounded" style="margin-top:50px">
        <h3 style="text-align:center ;">Data Kelas</h3>
        <form method="POST">
        {% csrf_token %}
    
        <div class="form-group">
            {{kelas_form.nama.label}}
            {{kelas_form.nama}}
        </div>
        <div class="form-group">
            {{kelas_form.kapasitas.label}}
            {{kelas_form.kapasitas}}
        </div>
        <div class="d-grid gap-2 d-md-block">
            <button type="submit" class="btn btn-primary btn-block">Kirim</button>
         </div>

    </form>
</div>
{% endblock contents %}

Aplikasi/CRUD/App/templates/kelas/list.html
{% extends "base.html" %}

{% block title %}
    {{page_title}}
{% endblock title %}


{% block contents %}
<div class="container shadow-lg p-3 mb-5 bg-white rounded" style="margin-top:50px">
<h3 style="text-align:center ;">Data Kelas</h3>
<a href="{% url 'App:createkelas' %}" class="btn btn-primary" role="button" aria-disabled="true">Create</a>
    <table class="table" style="margin-top:10px">
        <thead style="text-align:center ;">
            <tr>
                <th style="width: 30%;">Kelas</th>
                <th style="width: 30%;">Jumlah</th>
                <th style="width: 30%;">Action</th>
            </tr>
        </thead>
        <tbody style="text-align:center ;">
            {% for kelas in semua_kelas %}
              <tr>
                  <td style="width: 30%;">{{kelas.nama}}</td>
                  <td style="width: 30%;">{{kelas.kapasitas}}</td>
                  <td style="width: 15%;">
                    <a href="{% url 'App:deletekelas' kelas.id %}" class="btn btn-danger" role="button" aria-disabled="true">Delete</a>
                    <a href="{% url 'App:updatekelas' kelas.id %}" class="btn btn-success" role="button" aria-disabled="true">Update</a>
                </td>
              </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock contents %}